rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration
rauc/meta-rauc pull request #147
Opened 2020-10-02 10:17 UTC by ejoerns

This allows to build 'rauc' with default TUNE_PKGARCH while ony 'rauc-conf'
needs to be build for MACHINE_ARCH as it contains MACHINE-specific
configuration.

The rauc target package now RDEPENDS on rauc-conf.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

2021-08-23 20:43 UTC, ejoerns commented
rebased onto master

2021-08-24 08:38 UTC, OnkelUlla reviewed
Just two suggestions.

2021-08-24 08:38 UTC, OnkelUlla commented on recipes-core/rauc/rauc-conf.bb
> +        install -m 0644 ${WORKDIR}/system.conf ${D}${sysconfdir}/rauc/system.conf
Perhaps simplify in accordance to the installation of the keyring file:
```suggestion
        install -m 0644 ${WORKDIR}/system.conf ${D}${sysconfdir}/rauc/
```

2021-08-24 08:38 UTC, OnkelUlla commented on recipes-core/rauc/rauc-conf.bb
> +
What about
```suggestion

inherit allarch
```
here?

2021-08-24 08:49 UTC, jluebbe requested changes
With the `RDEPENDS += "rauc-conf"` it should be obvious enough to people updating from previous versions that the system.conf would need to move to `rauc-conf`. Perhaps add a hint regarding that to the commit message nevertheless?

2021-08-24 08:49 UTC, jluebbe commented on recipes-core/rauc/rauc-conf.bb
> +# Copyright (C) 2020 Enrico Jorns <ejo@pengutronix.de>
```suggestion
# Copyright (C) 2021 Enrico Jorns <ejo@pengutronix.de>
```

2021-08-24 08:51 UTC, jluebbe commented on recipes-core/rauc/rauc-conf.bb
> +
No, the config needs to be machine-specific.

2022-07-20 15:33 UTC, ejoerns commented
Indeed.

And I currently work myself on a project where this should be quite useful, too.
If I find the time, I will test this again in and make it ready for being merged.

2024-01-19 18:34 UTC, philippderdiedas commented
well...
how about know? (he asked nicely because does not want to fork it himself)

2024-02-08 22:33 UTC, ejoerns commented on recipes-core/rauc/rauc-conf.bb
> +# Copyright (C) 2020 Enrico Jorns <ejo@pengutronix.de>
I've simply removed this line.

2024-02-08 22:34 UTC, ejoerns commented on recipes-core/rauc/rauc-conf.bb
> +        install -m 0644 ${WORKDIR}/system.conf ${D}${sysconfdir}/rauc/system.conf
I kept it the same at first, making as few changes as necessary compared to the original recipe.

2024-02-08 22:41 UTC, ejoerns commented
Rebased onto the current `master` and applied some minor changes.

I was unsure about how strongly I wanted to couple `rauc` and `rauc-conf` and decided to add a `RRECOMMENDS` to a virtual package indirection since I assume that people not only need to want/need to append the `rauc-conf` recipe but likely provide their own recipes instead. E.g. for differentiating variants on the image level, this is required anyway.

Suggestions or objections welcome.

2024-02-12 10:02 UTC, jluebbe commented
> I was unsure about how strongly I wanted to couple `rauc` and `rauc-conf` and decided to add a `RRECOMMENDS` to a virtual package indirection since I assume that people not only need to want/need to append the `rauc-conf` recipe but likely provide their own recipes instead. E.g. for differentiating variants on the image level, this is required anyway.

Anyone using [`NO_RECOMMENDATIONS`](https://docs.yoctoproject.org/singleindex.html#term-NO_RECOMMENDATIONS) in their image will have no config in their image. If you want to use per-image configs, you can easily drop the RDEPENDS via a bbappend. A comment for that case should be enough.

2024-02-12 10:18 UTC, ejoerns commented
> > I was unsure about how strongly I wanted to couple `rauc` and `rauc-conf` and decided to add a `RRECOMMENDS` to a virtual package indirection since I assume that people not only need to want/need to append the `rauc-conf` recipe but likely provide their own recipes instead. E.g. for differentiating variants on the image level, this is required anyway.
> 
> With this change, anyone using [`NO_RECOMMENDATIONS`](https://docs.yoctoproject.org/singleindex.html#term-NO_RECOMMENDATIONS) in their image will have no config in their image. If you want to use per-image configs, you can easily drop the RDEPENDS via a bbappend. A comment for that case should be enough.

I wanted to avoid having to bbappend the recipe file for this case and assumed that having no config at all might be noticed.

Note that e.g. systemd pulls in systemd-conf via `RRECOMMENDS` only, too.

But maybe using `RDEPENDS` is safer for the transition in the first round, anyway.

2024-02-12 10:45 UTC, jluebbe commented
> I wanted to avoid having to bbappend the recipe file for this case and assumed that having no config at all might be noticed.
> 
> Note that e.g. systemd pulls in systemd-conf via `RRECOMMENDS` only, too.

OK. Then it's consistent, and it retract my criticism.
 
> But maybe using `RDEPENDS` is safer for the transition in the first round, anyway.

2024-02-12 10:46 UTC, jluebbe approved these changes

2024-02-29 09:09 UTC, merged