bundle: Add slot parameter for bootloader offset
rauc/meta-rauc pull request #155
Opened 2020-10-22 11:06 UTC by ctenruh-phytec

Option to set an offset in the slot parameter for the bootloader image. New bootloader image
with the set offset is created via "dd" command.

2020-10-22 14:12 UTC, mschwan-phytec requested changes

2020-10-22 14:12 UTC, mschwan-phytec commented on classes/bundle.bbclass
> +
Remove this additional empty line.

2020-10-22 14:12 UTC, mschwan-phytec commented on classes/bundle.bbclass
> +                                 "bs=1k", "seek=%s" % imgoffset])
You may want to use `'` instead of `"` for Python strings but that is just a minor thing to me. :wink:

2020-10-22 14:12 UTC, mschwan-phytec commented on classes/bundle.bbclass
> +                subprocess.call(["dd", d.expand("if=${DEPLOY_DIR_IMAGE}/%s" % imgsource),
I think you can use `searchpath` instead of `d.expand("if=${DEPLOY_DIR_IMAGE}/%s" % imgsource)` here...

2020-10-22 14:12 UTC, mschwan-phytec commented on classes/bundle.bbclass
> +                                 d.expand("of=${BUNDLE_DIR}/%s") % imgsource,
... and `bundle_imgpath` for this one.

2020-10-23 08:57 UTC, mschwan-phytec approved these changes
LGTM

2020-10-30 14:20 UTC, jluebbe commented
Is the 1kB granularity small enough? Why not use bytes?

2020-11-02 14:35 UTC, ejoerns commented
> Is the 1kB granularity small enough? Why not use bytes?

This can easily be achieved when adding `oflag=seek_bytes` to the dd call.

2020-11-03 10:34 UTC, ctenruh-phytec commented
thanks for the hints.

2020-11-04 01:28 UTC, ejoerns commented on classes/bundle.bbclass
> +# To use an offset in a bootloader image set the following parameter in bytes
`To use an offset` is a bit unspecific. What about `To prepend an offset`?

```suggestion
# To prepend an offset to a bootloader image, set the following parameter in bytes
```

The parameter could potentially also be appended by a common multiplikator as `dd` alows; e.g. `100K`  oder `1MB`

2020-11-04 20:33 UTC, ejoerns approved these changes
@ctenruh-phytec Thanks for your adjustments! Looks fine for me now! :+1:

2020-11-04 20:34 UTC, merged