rauc: rauc-mark-good: improve service unit
rauc/meta-rauc pull request #197
Opened 2021-08-23 16:26 UTC by Bastian-Krause

Make the rauc-mark-good.service run only if `bootchooser.active` or `rauc.slot` are set in the kernel command line. During
debugging/development, boot from NFS or non-bootchooser boots might be used. In these cases `rauc status mark-good` will fail.

`RemainAfterExit=yes` allows systemd to start dependencies only after `rauc status mark-good` has succeeded.

While at it, use the official RAUC spelling and remove the trailing empty line.

2021-08-24 06:44 UTC, OnkelUlla requested changes
Good idea to utilize ``ConditionKernelCommandLine=|...`` to start the unit only if the bootloader explicitely booted one or the other slot. But then the directive ``WantedBy=multi-user.target`` should be removed at the same time.

The introduction of ``RemainAfterExit=yes`` makes sense as well because it ensures that this service unit is only started once (see e.g. section "Example 4. Stoppable oneshot service" in the manpage for [systemd.service](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Examples)). Starting dependencies only after success of ``rauc status mark-good`` is already arranged by the choice of ``Type=oneshot`` compared to ``Type=simple``, so the commit message should be adjusted in that respect.

2021-08-24 08:02 UTC, jluebbe commented
> Good idea to utilize `ConditionKernelCommandLine=|...` to start the unit only if the bootloader explicitely booted one or the other slot. But then the directive `WantedBy=multi-user.target` should be removed at the same time.

I think `WantedBy` is still needed to activate the unit. Are you sure this works without it?

2021-08-24 08:51 UTC, Bastian-Krause commented
> The introduction of `RemainAfterExit=yes` makes sense as well because it ensures that this service unit is only started once (see e.g. section "Example 4. Stoppable oneshot service" in the manpage for [systemd.service](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Examples)). Starting dependencies only after success of `rauc status mark-good` is already arranged by the choice of `Type=oneshot` compared to `Type=simple`, so the commit message should be adjusted in that respect.

Correct, I misread the man page regarding that option. Will adjust the commit message.

2021-08-24 08:51 UTC, OnkelUlla commented
> I think `WantedBy` is still needed to activate the unit. Are you sure this works without it?

You are right and my understanding of triggering conditions was not correct, so please forget about my suggestion to remove ``WantedBy=multi-user.target``.

2021-08-24 08:58 UTC, OnkelUlla approved these changes
Looks good to me!

2021-08-25 12:49 UTC, ejoerns approved these changes

2021-08-25 12:50 UTC, merged

2022-02-04 16:27 UTC, ejoerns commented
Cherry-picked to 'dunfell' branch.