Add support for full custom update
rauc/meta-rauc pull request #201
Opened 2021-10-13 18:30 UTC by vivien

This PR adds support for full custom updates as well as simplifying the code a bit and enabling variable parsing in flags such as `RAUC_SLOT_rootfs[file] = "${SOME_FILE}"`.

2021-11-03 18:00 UTC, vivien commented
Any update on this? :eyes:

2022-10-27 20:56 UTC, ejoerns requested changes
Sorry for letting this unattended for longer. I was mainly a bit skeptical about making support for full custom updates too convenient since I don't really think that this is what users should do in 90% of use cases.
Over this the bug fixes contained here popped of my mental stack. But to be honest, they are unrelated to the title, anyway.

Thus I would propose to create a separate PR for the fixes and keep this PR for the full custom handler.

I would tend to merge full custom handler, too if the adaption I noted was made.

2022-10-27 20:56 UTC, ejoerns commented on classes/bundle.bbclass
> +		cp --no-preserve=ownership -r ${B}/casync-bundle.castr ${DEPLOYDIR}/${CASYNC_BUNDLE_NAME}.castr
Since this is nothing that is installed on the target, I am not sure if how host contamination plays a role here.

2022-10-27 20:56 UTC, ejoerns commented on classes/bundle.bbclass
> +    hooksflags = d.getVarFlags('RAUC_BUNDLE_HOOKS', ['file', 'hooks'])
Didn't knew this notation is possible, yet. I like this solution since it does not require to add additional `getVarFlag()` calls.

2022-10-27 20:56 UTC, ejoerns commented on classes/bundle.bbclass
> +RAUC_BUNDLE_HANDLER[doc] = "Allows to fully replace the default update process with a custom script (via varflags '[filename'] and ['args'])"
This is a really rarely used feature. Thus if we support it in the manifest, it should at least get a name that does not confuse with normal RAUC handlers and that clearly says you're doing something very custom.

Thus maybe `RAUC_BUNDLE_FULL_CUSTOM_HANDLER` or at least `RAUC_BUNDLE_CUSTOM_HANDLER`?

2022-10-27 20:56 UTC, ejoerns commented on classes/bundle.bbclass
> +        pn, task = ('%s:do_deploy' % image).split(':')[0:2]
this is way shorter but maybe a bit too magic to get at first sight later what we did here.
Could you add a short comment to clarify how 'fallback' to `do_deploy` works, here?

2024-01-07 22:24 UTC, ejoerns commented
Since most code of the `bundle.bbclass` is useless for full custom bundles, I find it misleading for others to implement the full custom update here. A distinct class might be a better solution.

Since the other fixes that were part of this PR were resolved by later PRs already, I'd close this now.
@vivien sorry for ignoring the useful fixes that were in here for too long.

2024-01-07 22:24 UTC, closed without merging