classes: bundle: support multiconfig dependencies for slots
rauc/meta-rauc pull request #207
Opened 2021-11-05 15:39 UTC by a3f

Users may want to populate a slot with an image resulting from a
multiconfig build. This can be especially useful with RAUC variants:

 - Same rootfs slots for both `MACHINE`s
 - different bootloader images, depending on `MACHINE`

For this to work out of the box, `bundle.bbclass` will need some
multiconfig awareness to emit `mcdepends` instead of `depends`
when depending on a multiconfig recipe.

With this addressed, following slots definition is now possible:
```
  RAUC_SLOT_bootloader-othermachine = "mc::othermachine:bootloader"
  RAUC_SLOT_bootloader-othermachine[name] = "bootloader.othermachine"
  RAUC_SLOT_bootloader-othermachine[type] = "boot"
  RAUC_SLOT_bootloader-othermachine[file] = "../othermachine/bootloader.img"
```
No functional change intended for non-multiconfig users.

2021-11-05 15:40 UTC, a3f commented
I have the equivalent on zeus and it works well. I left this as a draft until I can test this against a more up to date Yocto release. Comments welcome in the meantime though!

2022-12-23 14:19 UTC, ejoerns requested changes

2022-12-23 14:19 UTC, ejoerns commented on classes/bundle.bbclass
> +    def append_slot_depends(d, image, deptask=None):
Maybe rename `image` to `depends` here to avoid confusion since it is not necessarily an 'image' and it might also contain the deptask already.

2022-12-23 14:19 UTC, ejoerns commented on classes/bundle.bbclass
> +            d.appendVarFlag('do_unpack', 'mcdepends', ' ' + dependency)
I guess the `' '` is not required since we have a string already.

2022-12-23 15:06 UTC, a3f commented
In the meantime, I have added an intermediary recipe that does basically:
```
OTHERMACHINE_DEPLOYDIR= "../../../../tmp_mc-othermachine/deploy/images/othermachine"
do_deploy[mcdepends] += "mc::othermachine:originalrecipe:do_deploy
do_deploy () {
  cd ${DEPLOY_DIR_IMAGE}
  ln -sf ${OTHERMACHINE_DEPLOYDIR}/artifact-othermachine $ ${DEPLOYDIR}/
}
```

So I am no longer using the changes I originally submitted here. I will try to find some time in a few weeks to incorporate your feedback and retest.

2024-01-07 21:56 UTC, ejoerns commented
@a3f  Any update on this or interest in the topic? Or should we close this until someone needs mc deps again?

2024-01-08 15:59 UTC, a3f commented
Sorry, didn't find the time to address the feedback. As I don't currently use it, I'll close till there's renewed interest.

2024-01-08 15:59 UTC, closed without merging