recipes: Update LICENSE variable to use SPDX license identifiers
rauc/meta-rauc pull request #218
Opened 2022-03-07 10:23 UTC by matthiasklein

Signed-off-by: Matthias Klein <matthias@extraklein.de>

2022-03-07 10:39 UTC, rohieb requested changes

2022-03-07 10:39 UTC, rohieb commented on recipes-bsp/dt-utils/dt-utils.inc
>  LIC_FILES_CHKSUM = "file://COPYING;md5=9ac2e7cff1ddaf48b6eab6028f23ef88"
I would also include the snippet from README here as source for the `-only` part:
`file://README;beginline=39;md5=f139f662160ab6bc7eb412251d89d885`

2022-03-07 10:39 UTC, rohieb commented on recipes-casync/casync/casync_git.bb
> +LICENSE = "LGPL-2.1-only"
Hmm, at least https://github.com/systemd/casync/blob/master/src/cacache.c says "LGPL2.1+", that would be `-or-later`…?

2022-03-07 10:39 UTC, rohieb commented on recipes-core/rauc/rauc.inc
> +LICENSE = "LGPL-2.1-only"
Hmmm. I could only a LGPL license text, but no sign of `-or-later` or `-only` in any of the RAUC code, … @jluebbe, @ejoerns, could you clarify?

2022-03-07 10:39 UTC, rohieb commented on recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb
> +LICENSE = "LGPL-2.1-only"
The README says `either version 2.1 of the License, or (at your option) any later version`, I would add it to LIC_FILES_CHKSUM too: `file://README.rst;beginline=114;endline=132;md5=a569a9868bb81fb591cf2cdfdf61db1d`

2022-03-07 13:16 UTC, jluebbe commented on recipes-core/rauc/rauc.inc
> +LICENSE = "LGPL-2.1-only"
We don't have any `-only` restriction.

2022-03-27 14:32 UTC, matthiasklein commented
@rohieb I have reworked the PR according to your comments.

2022-03-27 15:24 UTC, matthiasklein commented
@rohieb The README file of dt-utils version 2021.03.0 does not have a relevant license section yet: https://git.pengutronix.de/cgit/tools/dt-utils/tree/README?h=v2021.03.0

2022-03-27 23:21 UTC, rohieb commented
> @rohieb The README file of dt-utils version 2021.03.0 does not have a relevant license section yet: https://git.pengutronix.de/cgit/tools/dt-utils/tree/README?h=v2021.03.0

Ah. Yes, my bad. I looked on the current master :-)

2022-03-29 20:03 UTC, ejoerns approved these changes

2022-03-30 21:08 UTC, rohieb approved these changes

2022-03-30 21:37 UTC, merged