Update RAUC git version to latest master
rauc/meta-rauc pull request #219
Opened 2022-03-18 14:45 UTC by ejoerns

Two major new features have found their way into RAUC since v1.6:

* native HTTP(S) streaming support
* bundle encryption

Update the git recipes to optionally allow building the current master.

Introduce convenience variable to enable development version, e.g. from local.conf:

    RAUC_USE_DEVEL_VERSION = "1"

2022-03-18 15:24 UTC, jluebbe requested changes

2022-03-18 15:24 UTC, jluebbe commented on recipes-core/rauc/rauc-git.inc
> +PACKAGECONFIG:class-target ??= "service network streaming json nocreate gpt"
How does this interact with
```
PACKAGECONFIG ??= "service network json nocreate gpt"
```
in rauc-target.inc?

2022-03-18 15:24 UTC, jluebbe commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION[doc] = "Global switch to enable RAUC development (git) version."
Perhaps a comment here how to enable it in `local.conf`?

2022-03-18 17:01 UTC, zyga commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION ??= "-1"
What does -1 imply here? I was expecting a 0 vs 1 flag.

2022-03-20 18:19 UTC, ejoerns commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION ??= "-1"
Ma idea was to simply select the same value that `DEFAULT_PREFERENCE` would take. The main purpose of this variable is to allow switching the DEFAULT_PREFERENCE of each RAUC package with a single variable.

For reference: The documentation says about `DEFAULT_PREFERENCE`:
> The most common usage of this is variable is to set it to “-1” within a recipe for a development version of a piece of software.

2022-03-20 18:33 UTC, ejoerns commented on recipes-core/rauc/rauc-git.inc
> +PACKAGECONFIG:class-target ??= "service network streaming json nocreate gpt"
Due to my change in 95d041ed56f296847b1cf8eeb89cc203d528cc87, this is now overridden with the new weak default as far as I can see.

2022-03-20 18:34 UTC, ejoerns commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION[doc] = "Global switch to enable RAUC development (git) version."
I'd then prefer adding a hint in README. Being able to set global variables in local.conf is not something worth being documented I guess.

2022-03-21 09:47 UTC, zyga commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION ??= "-1"
Ah, I see. Thank you for explaining this.

2022-03-25 10:12 UTC, ejoerns commented on recipes-core/rauc/rauc-git.inc
> +RAUC_USE_DEVEL_VERSION[doc] = "Global switch to enable RAUC development (git) version."
I have now added a section in the README

2022-03-25 10:14 UTC, ejoerns commented
I had to extend the change in include file handling a bit (see commit messasge).

The update now also comes with a new section in the README and enabling BLK_DEV_NBD in the kernel.

2022-03-31 13:49 UTC, ejoerns commented
Updated to latest master commit that contains some further fixes just merged.

2022-03-31 15:27 UTC, ejoerns commented
Bumped again. Now to https://github.com/rauc/rauc/commit/3963103bac7dc872c5ee42a2924a39474278af39 (latest master)

2022-03-31 15:46 UTC, merged

2022-10-13 20:54 UTC, ejoerns commented
partly cherry-picked to `dunfell` by #243