classes: bundle: Allow parsing var flags offset, hooks and adaptive
rauc/meta-rauc pull request #249
Opened 2022-10-25 13:26 UTC by mschwan-phytec

Allow for BitBake variable parsing inside the variable flags "offset", "hooks" and "adaptive". To enable this, use d.getVarFlag() instead of the builtin get() method.

2022-10-26 05:32 UTC, ejoerns requested changes
Good catch about the parsing handling.

But pretty sure this was only tested for `'offset'` :wink:

2022-10-26 05:32 UTC, ejoerns commented on classes/bundle.bbclass
> +            manifest.write("hooks=%s\n" % d.getVarFlag('RAUC_SLOT_%' % slot, 'hooks'))
```suggestion
            manifest.write("hooks=%s\n" % d.getVarFlag('RAUC_SLOT_%s' % slot, 'hooks'))
```

2022-10-26 05:32 UTC, ejoerns commented on classes/bundle.bbclass
> +            manifest.write("adaptive=%s\n" % d.getVarFlag('RAUC_SLOT_%' % slot, 'adaptive'))
```suggestion
            manifest.write("adaptive=%s\n" % d.getVarFlag('RAUC_SLOT_%s' % slot, 'adaptive'))
```

2022-10-26 07:39 UTC, mschwan-phytec commented
> Good catch about the parsing handling.
> 
> But pretty sure this was only tested for `'offset'` :wink:

Whoops! :grimacing: Fixed.

2022-10-26 07:43 UTC, ejoerns approved these changes

2022-10-26 14:11 UTC, merged

2022-10-27 07:46 UTC, mschwan-phytec commented
Can we backport this to kirkstone? As adaptive updates are available in kirkstone, too, it would fix the parsing there.

2022-10-27 19:47 UTC, ejoerns commented
cherry-picked to `kirkstone`