classes: bundle: warn if RAUC_BUNDLE_FORMAT is not set
rauc/meta-rauc pull request #250
Opened 2022-10-28 13:29 UTC by ejoerns

This is the next step towards deprecating the 'plain' format. We start enforcing an explicit decision whether to use old 'plain' or new 'verity' format.

And we guide the user to use 'verity' for new projects.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

2022-11-01 09:11 UTC, jluebbe reviewed
Looks good, but perhaps we should point to https://rauc.readthedocs.io/en/latest/reference.html#sec-ref-formats as well?

2022-11-17 06:01 UTC, ejoerns commented
Added the link to the documentation

2022-11-17 07:50 UTC, jluebbe requested changes

2022-11-17 07:50 UTC, jluebbe commented on classes/bundle.bbclass
> +        bb.warn('No RAUC_BUNDLE_FORMAT set. This will default to using deprecated \'plain\' format.'
We haven't deprecated 'plain' yet, so perhaps
```suggestion
        bb.warn('No RAUC_BUNDLE_FORMAT set. This will default to using lecacy \'plain\' format.'
```

2022-11-17 08:02 UTC, ejoerns commented on classes/bundle.bbclass
> +        bb.warn('No RAUC_BUNDLE_FORMAT set. This will default to using deprecated \'plain\' format.'
Ack (for 'legacy')

2022-11-17 08:40 UTC, jluebbe approved these changes

2022-11-17 11:44 UTC, merged

2022-11-17 11:44 UTC, ejoerns commented
I'd tend to backport this at least to `kirkstone` since I expect this to be out in the field for years. Any objections?