rauc: switch to meson
rauc/meta-rauc pull request #265
Opened 2023-03-07 16:52 UTC by ejoerns

With v1.9, RAUC switched to using meson. Autotools support is kept only for transition phase and might be removed in v1.10.

2023-03-07 18:47 UTC, jluebbe requested changes
Looks good otherwise.

2023-03-07 18:47 UTC, jluebbe commented on recipes-core/rauc/rauc.inc
> +PACKAGECONFIG[gpt]     = "-Dgpt=enabled,-Dgpt=disabled,util-linux"
Why do some options use true and others enabled?

2023-03-07 20:50 UTC, ejoerns commented on recipes-core/rauc/rauc.inc
> +PACKAGECONFIG[gpt]     = "-Dgpt=enabled,-Dgpt=disabled,util-linux"
Because some options are [booleans](https://mesonbuild.com/Build-options.html#booleans) and some are [features](https://mesonbuild.com/Build-options.html#features).

2023-03-08 07:36 UTC, jluebbe approved these changes

2023-03-08 11:23 UTC, paletteguy commented
@ejoerns Is this going to be backported / cherry-picked to kirkstone ?

2023-03-08 11:42 UTC, ejoerns commented
> @ejoerns Is this going to be backported / cherry-picked to kirkstone ?

I guess it has to be ported later, yes. But I would let this live in master first of all.

2023-03-08 11:42 UTC, merged

2023-07-07 11:07 UTC, ejoerns commented
cherry-picked to `kirkstone`