Add Two Ways of Adding Custom Meta-Data Or Settings to The Manifest
rauc/meta-rauc pull request #271
Opened 2023-06-06 10:55 UTC by ejoerns

With `RAUC_META_SECTIONS` there is a similar approach to how bundles are defined that allows to specify RAUC [meta data sections](https://rauc.readthedocs.io/en/latest/reference.html?highligh=meta#manifest) in the manifest.

With `RAUC_MANIFEST_EXTRA_LINES` any (RAUC-parsable) manifest information can be appended to a manifest.

2023-06-06 11:56 UTC, jluebbe requested changes
Looks good otherwise.

2023-06-06 11:56 UTC, jluebbe commented on classes-recipe/bundle.bbclass
> +#   RAUC_META_mydata[release-note] = "a few words here"
Also in the commit message:
```suggestion
#   RAUC_META_mydata[release-notes] = "a few words here"
```

2023-06-06 12:07 UTC, ejoerns commented on classes-recipe/bundle.bbclass
> +#   RAUC_META_mydata[release-note] = "a few words here"
Fixed :+1:

2023-06-06 12:10 UTC, jluebbe approved these changes

2023-06-15 06:39 UTC, BenediktCyranka commented
Works perfect

2023-06-15 07:15 UTC, merged

2023-07-07 11:06 UTC, ejoerns commented
cherry-picked to `kirkstone`