README.rst: add Contribution notes, add DCO, add backporting notes
rauc/meta-rauc pull request #276
Opened 2023-07-05 08:06 UTC by ejoerns

2023-07-06 07:46 UTC, OnkelUlla requested changes
At least the typo should be fixed. If we discuss following the evolution of the kernel's process of submitting patches is up to you.

2023-07-06 07:46 UTC, OnkelUlla commented on DCO
> +as used for the Linux kernel:
That [process](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin) evolved a little bit in the meantime in kernel versions [v5.10](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9f364b605f34e1c0b9847943f55db061d5a26bcb), [v5.11](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7d71788735608b1578e3615ff2646d3a089ff0a8) and [v6.3](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4563201f33a022fc0353033d9dfeb1606a88330) - do we want to follow?

2023-07-06 07:46 UTC, OnkelUlla commented on README.rst
> +`Developer’s Certificate of Origin
See my first nitpicking note regarding the DCO.

2023-07-06 07:46 UTC, OnkelUlla commented on README.rst
> +b) backport on your own an create a new pull request
```suggestion
b) backport on your own and create a new pull request
```

2023-07-07 07:21 UTC, ejoerns commented on DCO
> +as used for the Linux kernel:
I am unsure what affects us here. Most changes refer to git workflow over mail. The only change I see is that they seemed to have allowed contributing by pseudonym. Am I right?

Maybe we should not write 'same' process here anyway.

2023-07-07 07:25 UTC, jluebbe commented on DCO
> +as used for the Linux kernel:
Most changes did not affect the DCO, and we point only to the "Sign your work" section. Furthermore, we already accepted changes under pseudonym, so I don't see any need to diverge from the kernel here.

2023-07-07 07:31 UTC, ejoerns commented on README.rst
> +b) backport on your own an create a new pull request
Fixed this

2023-07-07 09:07 UTC, OnkelUlla commented on DCO
> +as used for the Linux kernel:
> Ok, just noted the other changes are in chapters we do not reference. Thus the difference is mentioning of `git commit -s` (which we already had), mentioning of `git revert -s`, and allowing pseudonyms.

That's correct.
And as already stated before: I don't really care if we follow that evolution or not, but if we don't then we should not talk of the _same_ process as found in the kernel.

2023-07-07 09:23 UTC, ejoerns commented on DCO
> +as used for the Linux kernel:
I have no strong opinion on pseudonyms. I prefer actual names but if I have to choose between pseudonym or no contribution I would take the pseudonym.

As it is the same for RAUC itself: @jluebbe Do you have an opinion? Otherwise we could just take the text from the kernel 1:1 and continue speaking about 'same'.

2023-08-02 08:36 UTC, ejoerns commented
Is anyone in the mood for a review? :smirk:

2023-08-20 13:48 UTC, merged