README: rauc-conf needs to be appended now instead of rauc
rauc/meta-rauc pull request #327
Opened 2024-06-18 06:01 UTC by ejoerns

With d51bab8f (rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration), users need to append rauc-conf instead of rauc when providing their device-specific configuration.

This was not reflected by the docs yet.

Also add an explicit migration note early in the README.rst.

2024-06-18 07:12 UTC, jluebbe approved these changes

2024-06-18 07:12 UTC, merged

2024-06-18 07:19 UTC, OnkelUlla requested changes
Looks good otherwise.

2024-06-18 07:19 UTC, OnkelUlla commented on scripts/README
>     `recipes-core/rauc/files` and add a simple rauc .bbappend file
Formally in line 19 this should be _"and add a simple rauc-conf .bbappend file"_, perhaps it would be better to just drop the first part and use _"and add a simple .bbappend file"_ instead.

2024-06-18 07:25 UTC, ejoerns commented on scripts/README
>     `recipes-core/rauc/files` and add a simple rauc .bbappend file
:+1:  I would be fine with both variants. Since the PR was merged a minute before your comment, feel free to open a new one with this additional fix.

2024-06-18 09:48 UTC, OnkelUlla commented on scripts/README
>     `recipes-core/rauc/files` and add a simple rauc .bbappend file
Done and already merged.

2024-07-03 13:18 UTC, ejoerns commented
backported to `scarthgap`