bundle.bbclass: extend do_bundle[file-checksums]
rauc/meta-rauc pull request #353
Opened 2024-11-15 16:52 UTC by grembeter

Rerun `do_bundle` task when `RAUC_CERT_FILE` or `RAUC_KEY_FILE` files have been changed on the disk.

2024-11-15 22:11 UTC, ejoerns requested changes
This looks really useful. Actually, both files are not part of `SRC_URI` and thus their checksum would not be recorded by default.

However, since (despite the name does not suggest it) both could also be PKCS#11 URIs, I guess using `False` for the boolean part is required here.

2024-11-16 07:55 UTC, grembeter commented
Unfortunately, I cannot test it with PKCS#11 URIs.

2024-11-16 22:23 UTC, ejoerns commented
> Unfortunately, I cannot test it with PKCS#11 URIs.

@grembeter That shouldn't matter. The point is that the URIs are not valid paths in the file system and thus cannot be tracked. And using `False` allows to have non-existing paths.

Thanks for updating the PR!

2024-11-16 22:23 UTC, ejoerns approved these changes

2024-11-26 20:45 UTC, merged

2025-04-14 15:58 UTC, ejoerns commented
cherry-picked to [scarthgap](https://github.com/rauc/meta-rauc/commit/d859468ae885fb847733852a9e9b5fdbe946e2fa)